### ISSUE TITLE
Test for multiplication

### ISSUE THREAD

**Issue by richelbilderbeek** [fabianPas/TCProject#1]
In [TestClass.cs](https://github.com/fabianPas/TCProject/blob/master/Tests/TestClass.cs) is see a test for multipication is lacking. 

For my projects, building on TCProject, I will need multiplication and I would like to have it decently tested.

**Comment by fabianPas** [comment]
Fixed in 536d00d @richelbilderbeek!

**Comment by richelbilderbeek** [comment]
Well done!
